export default [
    {
        avatarURL: "/images/avatars/strongseal.jpg",
        name: "fake selki",
        id: "1",
        resumed: false,
        chairURL: "/images/rooms/basic/arm-chair.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/bad.jpg",
        name: "fake erica",
        id: "2",
        resumed: false,
        chairURL: "/images/rooms/basic/blue-chair.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/scream.jpg",
        name: "fake dorian",
        id: "3",
        resumed: false,
        chairURL: "/images/rooms/basic/clawfoot-tub.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/purpleface.png",
        name: "fake mickey",
        id: "4",
        resumed: false,
        chairURL: "/images/rooms/basic/game-chair.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/fear.jpg",
        name: "fake melissa",
        id: "5",
        resumed: false,
        chairURL: "/images/rooms/basic/little-car.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/coop.jpg",
        name: "fake coop fan",
        id: "6",
        resumed: false,
        chairURL: "/images/rooms/basic/shopping-cart.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/rosie.jpg",
        name: "fake rosie",
        id: "7",
        resumed: false,
        chairURL: "/images/rooms/basic/tan-chair.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/rosie.jpg",
        name: "fake rosie 2",
        id: "8",
        resumed: false,
        chairURL: "/images/rooms/basic/grey-couch.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/rosie.jpg",
        name: "fake rosie 2",
        id: "12",
        resumed: false,
        chairURL: "/images/rooms/basic/grey-couch.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/rosie.jpg",
        name: "fake rosie 2",
        id: "11",
        resumed: false,
        chairURL: "/images/rooms/basic/grey-couch.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
    {
        avatarURL: "/images/avatars/rosie.jpg",
        name: "fake rosie 2",
        id: "10",
        resumed: false,
        chairURL: "/images/rooms/basic/grey-couch.svg",
        typing: true,
        lastTypingTimestamp: -1,
    },
];
